name: Sync Subversion to GitHub

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:        # Allows manual trigger

env:
  SVN_REPO_URL: "https://bbpress.svn.wordpress.org"
  GITHUB_REPO_URL: "https://github.com/${{ github.repository }}.git"

jobs:
  sync:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye
      options: --workdir /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          persist-credentials: true
          clean: false
          submodules: false
          lfs: false
          sparse-checkout: false

      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install -y git git-svn subversion jq curl

      - name: Prevent Concurrent Runs
        run: |
          if [ -f .sync-running ]; then
            if test ! $(find ".sync-running" -mmin +10); then
              echo "Sync already running. Exiting."
              exit 1
            fi
          fi
          touch .sync-running

      - name: Switch to Master Branch
        run: |
          git checkout master || git checkout -b master

      - name: Fetch SVN Changes & Rebase
        run: |
          # Fetch all SVN changes and rebase on top of master (trunk)
          git svn fetch --all
          git svn rebase

      - name: Process SVN Tags into Git Tags
        run: |
          git for-each-ref refs/remotes/tags | cut -d / -f 4- | while read ref; do
            git tag "$ref" "refs/remotes/tags/$ref" > /dev/null 2>&1
          done

      - name: Process SVN Branches into Git Branches
        run: |
          # List SVN branches from the SVN branches URL.
          # Adjust the URL pattern if necessary.
          svn list ${SVN_REPO_URL}/branches/ | grep -oE '[3-9]\.[0-9]' | while read branch; do
            # Create a Git branch named "<branch>-branch" tracking the SVN branch.
            git branch "${branch}-branch" "remotes/$branch" > /dev/null 2>&1 || true
            git checkout "${branch}-branch"
            # Only rebase and push if there are differences.
            if [ "$(git diff --name-only remotes/$branch | wc -l | awk '{print $1}')" -ne 0 ]; then
              git svn rebase "remotes/$branch"
              git push origin "${branch}-branch"
            fi
          done

      - name: Switch Back to Master
        run: git checkout master

      - name: Push All Branches and Tags to GitHub
        run: |
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          git push --all origin --force
          git push --tags origin --force

      - name: Remove Sync Lock
        run: rm -f .sync-running
